controller_manager_ns: moveit_simple_controller_manager
controller_list:
# Arm controller
  - name: /jaco/kinova/velocity_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - jaco2_joint_1
        - jaco2_joint_2
        - jaco2_joint_3
        - jaco2_joint_4
        - jaco2_joint_5
        - jaco2_joint_6
# Finger controller
  - name: /jaco/kinova/ee_velocity_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
        - jaco2_joint_finger_1
        - jaco2_joint_finger_2
        - jaco2_joint_finger_3