# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: 100

# Settings for ros_control hardware interface
hw_interface:
   joints:
       - jaco2_joint_1
       - jaco2_joint_2
       - jaco2_joint_3
       - jaco2_joint_4
       - jaco2_joint_5
       - jaco2_joint_6
       - jaco2_joint_finger_1
       - jaco2_joint_finger_2
       - jaco2_joint_finger_3

# Publish all joint states ----------------------------------
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
      - jaco2_joint_1
      - jaco2_joint_2
      - jaco2_joint_3
      - jaco2_joint_4
      - jaco2_joint_5
      - jaco2_joint_6
   constraints:
      goal_time: 5.0
      jaco2_joint_1:
          trajectory: 0.60
          goal:       0.15
      jaco2_joint_2:
          trajectory: 0.60
          goal:       0.15
      jaco2_joint_3:
          trajectory: 0.60
          goal:       0.15
      jaco2_joint_4:
          trajectory: 0.60
          goal:       0.15
      jaco2_joint_5:
          trajectory: 0.60
          goal:       0.15
      jaco2_joint_6:
          trajectory: 0.60
          goal:       0.15

# Joint Trajectory Controller for End Effector -------------------------------
ee_position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   joints:
       - jaco2_joint_finger_1
       - jaco2_joint_finger_2
       - jaco2_joint_finger_3
   constraints:
       goal_time: 5.0
       jaco2_joint_finger_1:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_finger_2:
           trajectory: 0.60
           goal:       0.15
       jaco2_joint_finger_3:
           trajectory: 0.60
           goal:       0.15